### ISSUE TITLE
Says Proton 7 not installed but it is

### ISSUE THREAD

**Issue by awinborne415** [dotaxis/7thDeck#26]
When I run the .sh it searches for Proton 7 and doesn't find it says its launching Steam and installing it. Proton 7 is already installed though. Do I need to put the folder somewhere specific for it to be able to find Proton 7?

**Comment by dotaxis** [comment]
Restart Steam and then run 7thDeck again.

If that doesn't fix it, upload your `7thDeck.log` so I can have a look at it.

**Comment by brianx87** [comment]
I'm having the same issue, script won't run without changing ownership then I get the same Proton 7 issue. Steam has been restarted and Proton 7 installed.

**Comment by dotaxis** [comment]
> I'm having the same issue, script won't run without changing ownership then I get the same Proton 7 issue. Steam has been restarted and Proton 7 installed.
> 
> This is the output.
> 
> ```
> ./install.sh
> ./install.sh: line 2: deps/functions.sh: No such file or directory
> ./install.sh: line 3: getSteamLibrary: command not found
> ./install.sh: line 3: getSteamLibrary: command not found
> ./install.sh: line 3: getSteamLibrary: command not found
> ./install.sh: line 4: getSteamLibrary: command not found
> ./install.sh: line 5: getSteamLibrary: command not found
> ./install.sh: line 6: getSteamLibrary: command not found
> ```

Please follow the instructions and download the entire project as a zip and not just the `install.sh`.
