### ISSUE TITLE
Not able to play in 16/9 1080p on my TV

### ISSUE THREAD

**Issue by Kaz-** [dotaxis/7thDeck#27]
Hello, first of all thank you very much for this great script. 

I only have a small issue, i'm trying to play it on my TV and it seems like i'm stuck in 16/10 with blackbars. I've set both 7th Heaven and Final Fantasy VII to 1920x1080 in steam launcher parameters, I've also set the 16/9 and 1920x1080 options in Game Driver menu in 7th Heaven, but everytimes i launch the game (from 7th Heaven) its 16/10 with black bars on the side. 

Also, the option in the game driver menu always reset to 16/10 and "Auto" in resolution. 

Any ideas ?

Thank you 😃  !

**Comment by dotaxis** [comment]
Did you disable the Steam Deck Auto-Config mod? It will override your Game Driver settings if it's enabled.

**Comment by Kaz-** [comment]
Oh okay, my bad, didn't knew it was about graphic settings, I don't know why, I always assumed it was about controller support ... 

For reference if anyone has the same issue, you'll also need to switch to 16:9 in Cosmos Limit Break mod if you're using it. 

It now works perfectly fine, thanks for your help :) !

**Comment by dotaxis** [comment]
Glad to hear it. I will add a note in a future version to disable the mod if wanting to play in docked mode.
