### ISSUE TITLE
7th Deck not Installing

### ISSUE THREAD

**Issue by IJNorth** [dotaxis/7thDeck#28]
So I'm looking to play Final Fantasy 7 for the first time, I've seen 7th Heaven and it looks incredible!

I've followed a guide and downloaded the zip file from the 7th Deck site.

I'm currently stuck on the install, I've right clicked on install.smh and selected "Run from Konsole".

To my frustration, I've been met with the following script:

Checking if Proton 7 is installed...OK! Checking if SteamLinuxRuntime 2.0 is installed...OK! Checking if FF7 is installed...OK!

Rebuilding Final Fantasy VII under Proton 7.0... 
pkill: killing pid 72864 failed: Operation not permitted 
pkill: killing pid 72875 failed: Operation not permitted 
pkill: killing pid 72880 failed: Operation not permitted

**Comment by dotaxis** [comment]
What distro?

**Comment by IJNorth** [comment]
> What distro?

I'm trying to install for Proton 7.0

**Comment by dotaxis** [comment]
On what Linux distro? What device? You haven't given me any information about what you're trying to install this on

**Comment by IJNorth** [comment]
> On what Linux distro? What device? You haven't given me any information about what you're trying to install this on

Apologies I'm trying to install this on my Steam deck OLED (SteamOS).   Linux 6.1.52

**Comment by dotaxis** [comment]
Try rebooting. Also try closing Steam (right click the icon in the bottom right and click Exit) and then running the script.

If neither of these work try running the script as root. You can do this by opening a terminal window in the folder the script is in and typing `sudo ./install.sh`

**Comment by IJNorth** [comment]
It worked ! Thank you so much - I rebooted and shut down steam and it's running the install.
