### ISSUE TITLE
Using an external disk steam library location for ff7 makes install silently fail

### ISSUE THREAD

**Issue by xdSora** [dotaxis/7thDeck#30]
### HAPPENED ON
Kernel: arch 6.6.19-1
KDE Plasma: 5.27.11
KDE Framework: 5.115.0
QT: 5.15.12
Graphics backend: X11

### REPRODUCE
If you open Steam, use the top left icon and go to Settings > storage.
When you have an additional drive added, and that drive is not located on the same physical drive as your steam installation, the setup script will "successfully" complete, but you will not see any .NET installation windows. Additionally, when you'll try running 7th Heaven (for example through steam), it will start for momentarily and then stop.

### TEMPORARY FIX
I did not look into why this happens, but to fix this issue, simply reinstall the game on the same drive as Steam is installed on. Thankfully this should not be much of an issue due to the game's relatively small disk requirements.

**Comment by dotaxis** [comment]
Can you post the contents of you `/etc/fstab`? Remove any sensitive information from it first.

The script does account for Steam libraries in other locations and on other drives so I'm not entirely sure what is causing this.

If you could please run it again trying to install to the location where it failed and then upload your `7thDeck.log` here that would also be great.

**Comment by xdSora** [comment]
``` 
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a device; this may
# be used with UUID= as a more robust way to name devices that works even if
# disks are added and removed. See fstab(5).
#
# <file system>             <mount point>  <type>  <options>  <dump>  <pass>
UUID=28F4-6D90                            /boot/efi      vfat    umask=0077 0 2
UUID=ec046f4f-c7e2-452c-9689-cf8a01a42f4d /              ext4    defaults,noatime 0 1
tmpfs                                     /tmp           tmpfs   defaults,noatime,mode=1777 0 0
/dev/disk/by-uuid/e6e69bea-3471-4874-b034-9958ffb76205 /mnt/e6e69bea-3471-4874-b034-9958ffb76205 auto nosuid,nodev,nofail,x-gvfs-show 0 0
/dev/nvme1n1p1 /mnt/nvme1n1p1 auto nosuid,nodev,nofail,x-gvfs-show,x-gvfs-name=970%20EVO 0 0
```
Anything of note here? I can provide the reinstall logs at a later date (kind of a pain to do the whole process atm)

**Comment by dotaxis** [comment]
Which drive did you have FF7 installed to where it wasn't working?

**Comment by xdSora** [comment]
Sorry for the late reply, the one under `/mnt/nvme1n1p1`

**Comment by dotaxis** [comment]
Is there a reason you are using `nosuid,nodev` on that device? I had one other occurrence where a user had similar flags and similar issues.

If you don't have a specific reason to be using those flags, please try changing the last line of your `/etc/fstab` to the following:
```
/dev/nvme1n1p1 /mnt/nvme1n1p1 auto defaults,nofail,x-gvfs-show,x-gvfs-name=970%20EVO 0 0
```

**Comment by dotaxis** [comment]
Closing this because it is an issue with your environment and not an issue with 7thDeck.

**Comment by dotaxis** [comment]
Because the script has been thoroughly tested and works fine with the default mount options. I had another user with a similar issue who narrowed it down to his own lack of either `suid, `dev`, or `exec`. It's not my responsibility to make sure it works on any combination of mount options and end user might have set. This is not an issue with my code.

**Comment by xdSora** [comment]
No worries, I simply opened an issue in the case of it being a simple fix. Maybe I'll try fixing it, but since the game is so light it just makes more sense to install it on the other drive and not waste time with it.
