### ISSUE TITLE
Installation failing, hang-ups, and syntax errors

### ISSUE THREAD

**Issue by JonathanSloan** [dotaxis/7thDeck#37]
When running the script I get the following warning, though the script still runs:
```
awk: line 12: syntax error at or near ,
```

Next I see the following:
```
Checking if Proton 9 is installed...
Not found! Launching Steam to install.
Press Enter when Proton 9 is done installing.
```

Proton 9 _IS_ installed, so I press enter and steam restarts/opens, but nothing else happens.

I commented out the Proton check, but the same issue occurred with SteamLinuxRuntime.
I tried deleting directories for Proton and SteamLinuxRuntime and then verifying them for a clean install based on a comment in your video, but no change.
I commented the SteamLinuxRuntime out as well, which resulted in the following:
```
Checking if FF7 is installed... awk: line 12: syntax error at or near ,
OK!
Found FF7 at !

awk: line 12: syntax error at or near ,
awk: line 12: syntax error at or near ,
awk: line 12: syntax error at or near ,
Rebuilding Final Fantasy VII under Proton 9...
Sign into the Steam account that owns FF7 if prompted.
Waiting for Steam...

Waiting for you to select an installation path...
```
The prompt to select a directory, so I did so, then got the following:
```
Installing to /home/userName/Games/Mods/7thheaven.

Downloading 7th Heaven...
/home/userName/.cache/7thHeaven-v3.5.1.0_Release.exe is ready to be installed.

Installing 7th Heaven...
mkdir: cannot create directory ‘/steamapps’: Permission denied

Applying patches...
cp: cannot stat '/home/userName/Games/Mods/7thheaven/Resources/FF7_1.02_Eng_Patch/ff7.exe': No such file or directory
cp: cannot create regular file '/steamapps/compatdata/39140/pfx/drive_c/windows/system32/': No such file or directory
./install.sh: line 157: /steamapps/compatdata/39140/pfx/drive_c/.windows-label: No such file or directory
./install.sh: line 158: /steamapps/compatdata/39140/pfx/drive_c/.windows-serial: No such file or directory

Adding 7th Heaven to Desktop and Launcher...

Adding 7th Heaven to Steam...

All done!
You can close this window and launch 7th Heaven from Steam or the desktop now.
```
No patches or further prompts show up. 7th Heaven is added to Steam, but doesn't work and gives an error about a missing FF7 prefix.

For further reference, I am using Pop_OS on a PC, not SteamOS on a desktop.

Thanks for all of your work on this!

**Comment by JonathanSloan** [comment]
If only I had seen your comment on the discord before adding an issue here. Installing Gawk fixed my Issue, so I am closing it. Thanks so much for this tool!

**Comment by dotaxis** [comment]
For future reference, this is a Pop! OS specific issue that can be solved with `sudo apt install gawk`.

Glad you were able to find the solution on your own.
