### ISSUE TITLE
7th Heaven seems to freeze with Proton 9.0-2(?).

### ISSUE THREAD

**Issue by BitingChaos** [dotaxis/7thDeck#40]
7th Heaven seems to freeze up with the current Proton 9.0-2 version that Steam uses. The app becomes unresponsive if you click anything.

Using GE-Proton9-7 seems to work.

To test, in the 7th Heaven.sh file, I commented out this line:

`PROTON=$(LIBRARY=$(getSteamLibrary 2805730) && [ -n "$LIBRARY" ] && echo "$LIBRARY/steamapps/common/Proton 9.0 (Beta)/proton" || echo "NONE")`

And added this line below it:

`PROTON=$(LIBRARY=$(getSteamLibrary 2805730) && [ -n "$LIBRARY" ] && echo "$HOME/.local/share/Steam/compatibilitytools.d/GE-Proton9-7/proton" || echo "NONE")`

Then 7th Heaven seemed to work fine then. 

Trying to use Valve's Proton 8, 7, or older got 7th Heaven to load, but then controls in FF7 wouldn't work. 

I'm not sure if this is something that can be fixed from your end. I don't know enough about this stuff to know how to fix it myself.

This was brought to my attention from a post on [reddit](https://www.reddit.com/r/SteamDeck/comments/1dj4ri3/help_with_7th_heaven_7th_deck_for_final_fantasy/), since it's now impacting other users. It looks like Proton 9.0-2 came out a week ago.

**Comment by dotaxis** [comment]
Oh lord. Can you test using Proton Experimental?

I am not sure how to deal with this moving forward. This will be the second time in the last few months that Valve has completely broken a totally stable setup for me. It is incredibly frustrating to have them force updates that introduce issues like this en masse.

7thDeck may have to move over to GE-Proton entirely. I'll investigate this as part of the Rust rewrite I'm working on.

**Comment by BitingChaos** [comment]
Strangely, it seems to be _working_ with 9.0-2/9.0 Beta today. Perhaps the program was **hanging** when trying to update its catalog? Although, I don't know why it was working when I switched to the GE Proton 9 version.

**Comment by dotaxis** [comment]
Finally got around to pulling my deck out and seeing what was up. The program was hanging indefinitely when any of the dropdown menus were activated after updating to 9.0-2.

Removing `dxvk.conf` from the 7th Heaven install folder fixes this, and the reason it was there in the first place has been fixed in Wine/Proton as well.

Thanks for the report.
