### ISSUE TITLE
Error: Could not start the .NET Desktop Runtime version 8.0.0.

### ISSUE THREAD

**Issue by Lexicon102** [dotaxis/7thDeck#44]
“Please make sure you have both the x86 and x64 editions installed. Try using the 7th Heaven exe installer, or visit https://dotnet.microsoft.com for more information.”

I have installed both editions of the 8.0.0 and 8.0.8 runtimes to my Final Fantasy 7 proton prefix and am still getting this error

**Comment by dotaxis** [comment]
Post your 7thDeck.log

**Comment by Lexicon102** [comment]
[7thDeck.log](https://github.com/user-attachments/files/17082412/7thDeck.log)

**Comment by Lexicon102** [comment]
"
########################################################################
#                             7thDeck v2.4                             #
########################################################################
#    This script will:                                                 #
#   1. Apply patches to FF7's proton prefix to accomodate 7th Heaven   #
#   2. Install 7th Heaven to a folder of your choosing                 #
#   3. Add 7th Heaven to Steam using a custom launcher script          #
#   4. Add a custom controller config for Steam Deck, to allow mouse   #
#      control with trackpad without holding down the STEAM button     #
########################################################################
#           For support, please open an issue on GitHub,               #
#   or ask in the #Steamdeck-Proton channel of the Tsunamods Discord   #
########################################################################


Checking if Proton 9 is installed... OK!
Found Proton at /home/deck/.local/share/Steam/steamapps/common/Proton 9.0 (Beta)/proton!

Checking if Steam Linux Runtime is installed... OK!
Found SLR at /run/media/deck/f1fefb10-1590-479a-ab7e-8e549a443ca3/steamapps/common/SteamLinuxRuntime_sniper/run!

Checking if FF7 is installed... OK!
Found FF7 at /run/media/deck/f1fefb10-1590-479a-ab7e-8e549a443ca3!

Rebuilding Final Fantasy VII under Proton 9...
Sign into the Steam account that owns FF7 if prompted.
Waiting for Steam...

Waiting for you to select an installation path...
Installing to /run/media/deck/f1fefb10-1590-479a-ab7e-8e549a443ca3/Modding Software/7th Heaven.

Downloading 7th Heaven...
/home/deck/.cache/7thHeaven-v4.0.0.0_Release.exe is ready to be installed.

Installing 7th Heaven...
wine: using kernel write watches, use_kernel_writewatch 2.
fsync: up and running.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.

Applying patches to 7th Heaven...

Applying patches to FF7...

Adding controller config...

Adding 7th Heaven to Desktop and Launcher...

Adding 7th Heaven to Steam...
steam.sh[39924]: Running Steam on steamos rolling 64-bit
steam.sh[39924]: STEAM_RUNTIME is enabled automatically
setup.sh[39999]: Steam runtime environment up-to-date!

All done!
You can close this window and launch 7th Heaven from Steam or the desktop now"


Did it wrong, might be easier this way

**Comment by dotaxis** [comment]
I edited your comment to add a code block.

Log looks fine. How are you running 7th Heaven after the install?

**Comment by Lexicon102** [comment]
Through the Steam shortcut made by the installer

**Comment by dotaxis** [comment]
Can't reproduce this. Make sure you are using a fresh install of FF7.

> I have installed both editions of the 8.0.0 and 8.0.8 runtimes to my Final Fantasy 7 proton prefix 
Also don't know what you mean by this. 7thDeck should handle all the dependencies.

**Comment by dotaxis** [comment]
There is also a 7thHeaven.log in the 7thDeck directory. Can you upload that? Use a code block by wrapping it in 3 backticks (` ``` `)

**Comment by Lexicon102** [comment]
> Can't reproduce this. Make sure you are using a fresh install of FF7.
> 
> > I have installed both editions of the 8.0.0 and 8.0.8 runtimes to my Final Fantasy 7 proton prefix
> 
> Also don't know what you mean by this. 7thDeck should handle all the dependencies.

I tried installing them myself to try and fix the problem. I suppose I could completely delete the game and remove the compatdata and try installing it again

**Comment by Lexicon102** [comment]
> > Can't reproduce this. Make sure you are using a fresh install of FF7.
> > > I have installed both editions of the 8.0.0 and 8.0.8 runtimes to my Final Fantasy 7 proton prefix
> > 
> > 
> > Also don't know what you mean by this. 7thDeck should handle all the dependencies.
> 
> I tried installing them myself to try and fix the problem. I suppose I could completely delete the game and remove the compatdata and try installing it again

This did indeed fix it. Thanks for your help and sorry for wasting your time

**Comment by dotaxis** [comment]
No problem! Glad it's working.
