### ISSUE TITLE
Doesn't work on Ubuntu 24.04 due to AppArmor missing bwrap profile (solution provided)

### ISSUE THREAD

**Issue by bglogic** [dotaxis/7thDeck#45]
Following the instructions in the README file results in a broken installation which fails to run 7th Heaven. This is due to Ubuntu not having an AppArmor profile for `bwrap`. This is due to [restricted unprivileged user namespaces introduced in Ubuntu since 23.10](https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces).

As mentioned in [this comment](https://github.com/DevToys-app/DevToys/issues/1198#issuecomment-2411370778) the solution is to install the `apparmor-profiles` package, link the `bwrap` profile, and load it.

Here are the steps:

```bash
sudo apt install apparmor-profiles
sudo ln -s /usr/share/apparmor/extra-profiles/bwrap-userns-restrict /etc/apparmor.d/
sudo apparmor_parser /etc/apparmor.d/bwrap-userns-restrict
```

After following the steps 7thDeck's `install.sh` script will properly install 7th Heaven and the app will work as expected.

You can mention in the README that distros with AppArmor without a `bwrap` profile would fail the installation and add the above steps as a fix for Ubuntu.

**Comment by dotaxis** [comment]
Thanks for this report! Would you mind submitting a PR with an updated readme? A "distro-specific tweaks" section would be a good opportunity for me to also mention that `gawk` needs to be installed on PopOS for 7thDeck to work.
